// PDF generation (jsPDF + autotable) for issue slips, POs, GRNs, vouchers, gate passes
import { state, dt, dtm, money } from './lib.js';

const BRAND = [138, 90, 43];

export function makePdf({ title, no, date, meta = [], columns, rows, totals = [], notes = '', signatures = [], filename, landscape = false, subtitle = '' }) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: landscape ? 'landscape' : 'portrait', unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const c = state.company || {};

  // company header
  doc.setFillColor(...BRAND); doc.rect(0, 0, W, 3, 'F');
  doc.setFont('helvetica', 'bold'); doc.setFontSize(13); doc.setTextColor(40);
  doc.text(c.company_name || 'Citi Homes', 14, 14);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(90);
  const addr = [c.address, [c.phone, c.email].filter(Boolean).join('  |  '), c.trn ? 'TRN: ' + c.trn : ''].filter(Boolean);
  addr.forEach((l, i) => doc.text(String(l), 14, 19 + i * 4));

  // title block
  doc.setFont('helvetica', 'bold'); doc.setFontSize(15); doc.setTextColor(...BRAND);
  doc.text(title.toUpperCase(), W - 14, 14, { align: 'right' });
  doc.setFontSize(10); doc.setTextColor(40);
  doc.text(no || '', W - 14, 20, { align: 'right' });
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9);
  doc.text('Date: ' + dt(date), W - 14, 25, { align: 'right' });
  if (subtitle) doc.text(subtitle, W - 14, 30, { align: 'right' });

  // meta (two columns of label: value)
  let y = 36;
  doc.setDrawColor(220); doc.line(14, y - 3, W - 14, y - 3);
  const half = Math.ceil(meta.length / 2);
  const colX = [14, W / 2 + 2];
  doc.setFontSize(8.5);
  meta.forEach(([l, v], i) => {
    const col = i < half ? 0 : 1;
    const row = i < half ? i : i - half;
    const yy = y + row * 5;
    doc.setFont('helvetica', 'bold'); doc.setTextColor(90); doc.text(String(l) + ':', colX[col], yy);
    doc.setFont('helvetica', 'normal'); doc.setTextColor(30);
    doc.text(doc.splitTextToSize(String(v ?? ''), W / 2 - 50)[0] || '', colX[col] + 34, yy);
  });
  y += half * 5 + 3;

  doc.autoTable({
    startY: y,
    head: [columns.map(c => c.h)],
    body: rows.map(r => columns.map(c => (typeof c.k === 'function' ? c.k(r) : r[c.k]) ?? '')),
    styles: { fontSize: 8.5, cellPadding: 1.8, lineColor: [225, 225, 225], lineWidth: 0.1 },
    headStyles: { fillColor: BRAND, textColor: 255, fontStyle: 'bold' },
    columnStyles: Object.fromEntries(columns.map((c, i) => [i, { halign: c.align || 'left', cellWidth: c.w || 'auto' }])),
    margin: { left: 14, right: 14, bottom: 30 },
  });
  y = doc.lastAutoTable.finalY + 6;

  if (totals.length) {
    doc.setFontSize(9.5);
    totals.forEach(([l, v], i) => {
      doc.setFont('helvetica', i === totals.length - 1 ? 'bold' : 'normal');
      doc.text(String(l), W - 60, y + i * 5.5);
      doc.text(String(v), W - 14, y + i * 5.5, { align: 'right' });
    });
    y += totals.length * 5.5 + 3;
  }
  if (notes) {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5); doc.setTextColor(70);
    const lines = doc.splitTextToSize(notes, W - 28);
    if (y + lines.length * 4 > H - 40) { doc.addPage(); y = 20; }
    doc.text(lines, 14, y); y += lines.length * 4 + 4;
  }

  // signatures
  if (signatures.length) {
    let sy = Math.max(y + 18, H - 38);
    if (sy > H - 20) { doc.addPage(); sy = H - 38; }
    const w = (W - 28) / signatures.length;
    doc.setFontSize(8.5); doc.setTextColor(60); doc.setDrawColor(150);
    signatures.forEach((s, i) => {
      const x = 14 + i * w;
      doc.line(x + 3, sy, x + w - 6, sy);
      const [name, sub] = Array.isArray(s) ? s : [s, ''];
      doc.text(name, x + 3, sy + 4.5);
      if (sub) { doc.setTextColor(120); doc.text(String(sub), x + 3, sy + 8.5); doc.setTextColor(60); }
    });
  }

  // footer
  const pages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFontSize(7.5); doc.setTextColor(140);
    doc.text(`Generated by Citi Homes IMS · ${dtm(new Date().toISOString())} · ${state.profile?.full_name || state.profile?.email || ''}`, 14, H - 8);
    doc.text(`Page ${p} of ${pages}`, W - 14, H - 8, { align: 'right' });
  }
  doc.save(filename || `${(no || title).replace(/[\/\\]/g, '-')}.pdf`);
}

export const m = money;
